AWSTemplateFormatVersion: "2010-09-09"
Description: "A load balancer"
Resources:
  MySG:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupName: "mmark-LB-StaticEC2SecurityGroup"
      GroupDescription: "Inbound Access Rules for Static EC2 Web Access"
      SecurityGroupIngress:
        - CidrIp: "0.0.0.0/0"
          Description: "Inbound HTTP Access from the Internet"
          FromPort: "80"
          IpProtocol: "tcp"
          ToPort: "80"
      VpcId: !ImportValue mmark-demo-vpcid
  LoadBalancer:
    Type: AWS::ElasticLoadBalancingV2::LoadBalancer
    Properties:
      Scheme: "internet-facing"
      SecurityGroups:
        - !Ref MySG
      Subnets: !Split [ ",", !ImportValue mmark-demo-subnetids]
  MyTG:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Port: 80
      Protocol: "HTTP"
      VpcId: !ImportValue mmark-demo-vpcid
  MyLN:
    Type: AWS::ElasticLoadBalancingV2::Listener
    Properties:
      LoadBalancerArn: !Ref LoadBalancer
      Port: 80
      Protocol: "HTTP"
      DefaultActions:
        - Type: "forward"
          TargetGroupArn: !Ref MyTG
  MySSMPTG:
    Type: AWS::SSM::Parameter
    Properties:
      Name: mmark-targetgroupparam
      Type: "String"
      Value: !Ref MyTG
Outputs:
  LoadBalancerDNS:
    Description: "The DNS of the load balancer"
    Value: !GetAtt LoadBalancer.DNSName

